---
- name: Make Sure Forgejo runner instace address is set
  ansible.builtin.fail:
    msg: "Please set forgejo_runner__instance_address"
  when: forgejo_runner__instance_address == ''

- name: Make Sure Forgejo runner uuid is set
  ansible.builtin.fail:
    msg: "Please set forgejo_runner__uuid"
  when: forgejo_runner__uuid == ''

- name: Make Sure Forgejo runner token is set
  ansible.builtin.fail:
    msg: "Please set forgejo_runner__token"
  when: forgejo_runner__token == ''
  
- name: Create config with correct permissions
  become: true
  ansible.builtin.template:
    src: "forgejo_config.yaml.j2"
    dest: "{{ forgejo_runner__user_home }}/config.yaml"
    owner: "{{ forgejo_runner__user }}"
    group: "{{ forgejo_runner__group }}"
    mode: '0600'
  notify:
    - 'systemctl restart forgejo-runner'
